# Generated by Django 5.1.7 on 2025-03-29 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuecategory',
            name='is_public',
        ),
    ]
