# Generated by Django 5.1.7 on 2025-03-29 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_remove_issuecategory_is_public'),
    ]

    operations = [
    ]
